import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Link from "next/link";
import styles from "./styles.module.css";
import Header from "../components/Header/header";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="dark" lang="en">
      <body className={styles.body}>
        <Header />
        {/* <div className={styles.header}>
          <div>
            <Link href="/">ANASAYFA</Link>
          </div>
          <div className="flex gap-6">
            <Link href="/duyurular">Duyurular</Link>
            <Link href="/faaliyetler">Faaliyetler</Link>
            <Link href="/hakkimizda">Hakkımızda</Link>
          </div>
        </div> */}
        {children}

        <footer className="bg-blue-800 text-white">
          <div className="mx-auto text-center">
            <p className="text-sm">2023 Your Website. All rights reserved.</p>
            {/* Navigation links */}
            <nav className="mt-2 flex flex-col mx-auto">
              <Link
                className="text-gray-300 hover:text-white mx-auto"
                href="/hakkimizda"
              >
                Hakkımızda
              </Link>
              <Link
                className="text-gray-300 hover:text-white mx-auto"
                href="/faaliyetler"
              >
                Faaliyetler
              </Link>
              <Link
                className="text-gray-300 hover:text-white mx-auto"
                href="/duyurular"
              >
                Duyurular
              </Link>
            </nav>
          </div>
        </footer>
      </body>
    </html>
  );
}
