import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-blue-300 flex gap-6 text-red-900 items-center justify-between h-20 px-10">
          <div>
            <Link href="/">ANASAYFA</Link>
          </div>
          <div className="flex gap-6">
            <Link href="/duyurular">Duyurular</Link>
            <Link href="/faaliyetler">Faaliyetler</Link>
            <Link href="/hakkimizda">Hakkımızda</Link>
          </div>
        </div>
        {children}

        <footer className="bg-blue-800 text-white p-4">
          <div className="container mx-auto text-center">
            <p className="text-sm">
              &copy; 2023 Your Website. All rights reserved.
            </p>
            {/* Navigation links */}
            <nav className="mt-2">
              <Link href="/hakkimizda">
                <p className="text-gray-300 hover:text-white mx-2">
                  Hakkımızda
                </p>
              </Link>
              <Link href="/faaliyetler">
                <p className="text-gray-300 hover:text-white mx-2">
                  Faaliyetler
                </p>
              </Link>
              <Link href="/duyurular">
                <p className="text-gray-300 hover:text-white mx-2">Duyurular</p>
              </Link>
            </nav>
          </div>
        </footer>
      </body>
    </html>
  );
}
