import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="grid grid-cols-[200px_1fr] h-full">
        <nav className="flex flex-col gap-2 bg-blue-200 h-screen">
          <Link
            className="hover:bg-red-200 hover:text-white"
            href="/dashboard/faaliyetler"
          >
            Faaliyetler
          </Link>
          <Link className="hover:bg-red-200 hover:text-white" href="/dashboard/duyurular">
            Duyurular
          </Link>
          <Link className="hover:bg-red-200 hover:text-white" href="/dashboard/hakkimizda">
            Hakkımızda
          </Link>
        </nav>

        {children}
      </body>
    </html>
  );
}
