import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Link from "next/link";
import styles from "./styles.module.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={styles.root}>
        <nav className={styles.nav}>
          <Link
            className={styles.link}
            href="/dashboard/faaliyetler"
          >
            Faaliyetler
          </Link>
          <Link
            className={styles.link}
            href="/dashboard/duyurular"
          >
            Duyurular
          </Link>
          <Link
            className={styles.link}
            href="/dashboard/hakkimizda"
          >
            Hakkımızda
          </Link>
        </nav>

        {children}
      </body>
    </html>
  );
}
